pipeline {
    agent {
        label ('nodejs')
    }
    tools {
        nodejs ("nodejs-agent-1")
    }
    
    stages {
        stage ('Compress-js-css-files') {
            parallel {
                stage ('uglify-js') {
                    steps {
                        nodejs(nodeJSInstallationName: 'nodejs-agent-1') {
                            sh 'uglifyjs -o www/min/*.js www/js/*.js'
                            
                        }
                    }
                }
                stage ('clean-css') {
                    steps {
                        nodejs(nodeJSInstallationName: 'nodejs-agent-1') {
                            sh 'cleancss -o www/min/*.css www/css/*.css'
                            
                        }
                    }
                }
                
            }
        }
        stage('Package') {
            steps {
                sh 'mkdir artifacts'
                
                sh "tar --exclude ='./www/js/*' --exclude='./www/css'  --exclude='.git' --exclude='artifacts' -czvf  artifacts/compressed.${BUILD_ID}.tar.gz ."
             
                archiveArtifacts artifacts: "artifacts/compressed.${env.BUILD_ID}.tar.gz", fingerprint: true
            }
        }
       stage ('upload') {
           steps {
            gitlabCommitStatus("upload") {
                def server = Artifactory.server "artifactory@Jfrog"
                def buildInfo = Artifactory.newBuildInfo()
                buildInfo.env.capture = true
                buildInfo.env.collect()

                def uploadSpec = """{
                    "files": [
                {
                    "pattern": "artifacts/compressed.${BUILD_ID}.tar.gz",
                    "target": "default-generic-local/compressed.${BUILD_ID}.tar.gz"
                }
                  ]
                }"""
                // Upload to Artifactory.
                server.upload spec: uploadSpec, buildInfo: buildInfo

                buildInfo.retention maxBuilds: 10, maxDays: 7, deleteBuildArtifacts: true
                 // Publish build info.
                server.publishBuildInfo buildInfo
        }
        }
       }
    }
}
